# Generated by Django 4.2.3 on 2023-07-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(db_column='parent_category', default=1, on_delete=django.db.models.deletion.PROTECT, to='mimir.category'),
        ),
    ]
