# Generated by Django 4.2.3 on 2023-07-30 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimir', '0002_alter_category_parentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='lastReviewOn',
            field=models.DateField(db_column='last_review_on', default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='category',
            name='parentCategory',
            field=models.ForeignKey(db_column='parent_category', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mimir.category'),
        ),
    ]
