# Generated by Django 4.2.3 on 2023-07-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mimir', '0003_alter_card_lastreviewon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='category',
            field=models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='card', to='mimir.category'),
        ),
    ]
